image: ${DEVOPS_REGISTRY}usgs/centos:8

stages:
  - build

.check_code:
  after_script:
    # runs before cache is saved (copying from .travis.yml)
    - rm -f  "${CI_PROJECT_DIR}/.gradle/caches/modules-2/modules-2.lock"
    - rm -fr "${CI_PROJECT_DIR}/.gradle/caches/*/plugin-resolution/"
  before_script:
    # install dependencies
    - echo "cachedir=${CI_PROJECT_DIR}/.yum/\$$basearch/\$$releasever" >> /etc/yum.conf
    - if [ "$JAVA_EPEL" = "true" ]; then yum install -y epel-release; fi
    - yum install -y $JAVA_PACKAGE which
  cache:
    paths:
      - .gradle/caches
      - .gradle/wrapper
      - .yum
  script:
    # run gradle
    - export GRADLE_USER_HOME="${CI_PROJECT_DIR}/.gradle"
    - ./gradlew --info --no-daemon build
  stage: build
  tags:
    - development
  variables:
    JAVA_EPEL: "false"
    JAVA_PACKAGE: "java-11-openjdk-devel"

Java 8:
  extends:
    - .check_code
  variables:
    JAVA_PACKAGE: "java-1.8.0-openjdk-devel"

Java 11:
  artifacts:
    paths:
      - build/libs/ProductClient.jar
    reports:
      cobertura: build/reports/cobertura/cobertura.xml
      junit: build/test-results/test/TEST-*.xml
  extends:
    - .check_code
  variables:
    JAVA_PACKAGE: "java-11-openjdk-devel"

Java Latest:
  extends:
    - .check_code
  variables:
    JAVA_EPEL: "true"
    JAVA_PACKAGE: "java-latest-openjdk-devel"
